### ISSUE TITLE
Make service production deployable

### ISSUE THREAD

**Issue by rhysyngsun** [digitalcredentials/sign-and-verify#1]
- [x] Write `Dockerfile` for building docker images (https://github.com/digitalcredentials/sign-and-verify/pull/2)
  - ~~Probably use `docker-compose` for ease of use with local test configuration~~
- [x] Extract `unlocked-did.json` into a base64-encoded environment variable (secret)
  - Update/remove hardcoded usages of these values to use this
- [x] Setup GitHub Actions workflow for CI tests (https://github.com/digitalcredentials/sign-and-verify/pull/3)
- [ ] **Backlogged:** Setup GitHub Actions workflow for docker build/release
- [x] Improve test coverage
- [x] Update readme to reflect the above changes along the way

**Comment by kimdhamilton** [comment]
Some notes:
- preloadedDocs is passed to the json-ld libraries in order to pre-load any URLs in the credential. The primary use is for preloading json-ld contexts and DID documents so they're not being fetched at runtime. I think I'm leaning towards keeping the secret management sides separate, but I may not be groking the intent of item 2. We can discuss
- +1 to everything else. The only caveat is that we want to keep a "demonstration" ready path with throwaway keys, but we can easily do that in a compatible way that lets this also be useful for real use.

**Comment by rhysyngsun** [comment]
Closing since we've accomplished the majority of this work and the service has been successfully deployed.
