### ISSUE TITLE
need an anonymous audit log that is checked by the verifier (every time a credential is verified)

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/sign-and-verify#69]
An audit log isn't effective at detecting fraudulent issuance if it isn't checked at verification time (every time a credential is verified).

To explain, assume a fake credential has been issued by someone who has stolen the private signing key.  If all the verifier does is check that the signature is valid then that fake credential will always verify as authentic.  Even if we have somehow logged all known issuances, if we don't check that log at verification time, the fake goes undetected.

So, we can instead create a public log of known-to-be-issued credentials and check that log at verification time, and then if the fake credential isn't in the log, verification fails.  

Whoever signed the fake credential could also, of course, add a fake log entry.  We protect against that by auditing the log periodically, comparing all its entries to what we know are the 'true' list of authentic credentials.  That 'true' list might be say the backend database of a university student system.

The next problem is that the log can't contain PII because it is public.  We get around that by only publishing hashes of the credentials to the log.  The audit process therefore has to be able to regenerate the hashes of all the 'authentic' credentials, to compare with the set in the log.

Finally, we want to avoid the 'phone-home' problem with the log, so we want to ideally publish the log somewhere such that lookups in the log can't be monitored (otherwise whoever controls the log could observe who was checking a given credential, assuming they knew which hash matched which credential, which the issuer would know).  Blockcerts handles this by publishing its log to a public blockchain like Bitcoin - any call to the Bitcoin blockchain is pretty much anonymous, especially if a verifier hosts its own Bitcoin node).

There a few problems with Bitcoin though, among them that the environmental cost of transactions borders on ridiculous, but this can be dealt with by using a non-proof-of-work blockchain like the new Ethereum.  More significantly, though are that anything that is posted to a public blockchain, including Ethereum, is permanent.  Which makes it impossible to manage privacy law requirements like a right-to-be-forgotten request.  And even though our log only contains hashes, it may well be that laws like GDPR require that even hashes be removed on request.  There is also the problem with blockchains that transaction costs may become exorbitant, especially if we are doing a lot of individual issuances.  

So, an alternative is to publish the log somewhere besides a blockchain.  We might, for example, put our big list of hashes into a file at a CDN.  A new problem then becomes: how do we know that the list of hashes (that we've put into a big file at a CDN) hasn't been tampered with.  One possible solution is to publish checksums of all our CDN files somewhere trustworthy, like the issuer's web site.  The checksums are effectively the audit of the log.  We recalculate the checksums periodically, using back end data.

This seems like a good compromise because we can now remove hashes if we need to, we have created a distribution mechanism where it is difficult to monitor who is looking up what hash, and we detect fake issuances.

**Comment by bmuramatsu** [comment]
Before going too far down this path, I think we should check GDPR compliance (and/or ask TUM how they’re approaching this).

On Oct 19, 2022, at 2:41 PM, James Chartrand ***@***.***> wrote:

﻿

An audit log isn't effective at detecting fraudulent issuance if it isn't checked at verification time (every time a credential is verified).

To explain, assume a fake credential has been issued by someone who has stolen the private signing key. If all the verifier does is check that the signature is valid then that fake credential will always verify as authentic. Even if we have somehow logged all known issuances, if we don't check that log at verification time, the fake goes undetected.

So, we can instead create a public log of known-to-be-issued credentials and check that log at verification time, and then if the fake credential isn't in the log, verification fails.

Whoever signed the fake credential could also, of course, add a fake log entry. We protect against that by auditing the log periodically, comparing all its entries to what we know are the 'true' list of authentic credentials. That 'true' list might be say the backend database of a university student system.

The next problem is that the log can't contain PII because it is public. We get around that by only publishing hashes of the credentials to the log. The audit process therefore has to be able to regenerate the hashes of all the 'authentic' credentials, to compare with the set in the log.

Finally, we want to avoid the 'phone-home' problem with the log, so we want to ideally publish the log somewhere such that lookups in the log can't be monitored (otherwise whoever controls the log could observe who was checking a given credential, assuming they knew which hash matched which credential, which the issuer would know). Blockcerts handles this by publishing its log to a public blockchain like Bitcoin - any call to the Bitcoin blockchain is pretty much anonymous, especially if a verifier hosts its own Bitcoin node).

There a few problems with Bitcoin though, among them that the environmental cost of transactions borders on ridiculous, but this can be dealt with by using a non-proof-of-work blockchain like the new Ethereum. More significantly, though are that anything that is posted to a public blockchain, including Ethereum, is permanent. Which makes it impossible to manage privacy law requirements like a right-to-be-forgotten request. And even though our log only contains hashes, it may well be that laws like GDPR require that even hashes be removed on request. There is also the problem with blockchains that transaction costs may become exorbitant, especially if we are doing a lot of individual issuances.

So, an alternative is to publish the log somewhere besides a blockchain. We might, for example, put our big list of hashes into a file at a CDN. A new problem then becomes: how do we know that the list of hashes (that we've put into a big file at a CDN) hasn't been tampered with. One possible solution is to publish checksums of all our CDN files somewhere trustworthy, like the issuer's web site. The checksums are effectively the audit of the log. We recalculate the checksums periodically, using back end data.

This seems like a good compromise because we can now remove hashes if we need to, we have created a distribution mechanism where it is difficult to monitor who is looking up what hash, and we detect fake issuances.

**Comment by kayaelle** [comment]
Suggest we close since we are refactoring sign-and-verify and should have factored this into the new plan. Leaving open to follow-up on that documentation.
