### ISSUE TITLE
Allow passing contexts in to sign-and-verify-core

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/sign-and-verify#76]
Right now contexts are hard-coded into sign-and-verify-core:

https://github.com/digitalcredentials/sign-and-verify-core/blob/9505e8ce70b99abf5a1f3f11db94656de2862e6f/src/common.ts#L15

Should allow contexts to be passed in to sign-and-verify-core, probably here:

https://github.com/digitalcredentials/sign-and-verify-core/blob/9505e8ce70b99abf5a1f3f11db94656de2862e6f/src/issuer.ts#L8

**Comment by kayaelle** [comment]
@jchartrand Do you think this issue covers what we discussed in our call today to allow for contexts to be pulled from the web?

**Comment by bmuramatsu** [comment]
What are the security implications of letting any context be pulled in, in
our apps? Having written that, should this be a feature flag? Allow web
contexts for a given sign and verify install?

**Comment by kayaelle** [comment]
We discussed doing this only for our version that we've stood up for plugfest so that we can accept credentials from chapi.io playground that aren't open badges. But we should talk a little more about the implementation - how will we do this so that it will only affect our instance? 

It's an interesting question to consider for a feature flag...

**Comment by kezike** [comment]
> Right now contexts are hard-coded into sign-and-verify-core:
> 
> https://github.com/digitalcredentials/sign-and-verify-core/blob/9505e8ce70b99abf5a1f3f11db94656de2862e6f/src/common.ts#L15

Correction: this section actually handles loading remote http contexts: https://github.com/digitalcredentials/sign-and-verify-core/blob/main/src/verifier.ts#L94
